### ISSUE TITLE
Anyway to make this work on ubuntu?

### ISSUE THREAD

**Issue by ReznorMD** [AronParker/AviRecorder#13]
I have downloaded a replacement for net framework 4.6.2 on WIne (link- http://repacks.net/forum/viewtopic.php?t=7) but whenever i try to open the program it says "archive not avaliable." I have tried opening it manually from terminal but nothing works. Any idea how I can port it?

**Comment by AronParker** [comment]
Sorry for the late response. Unfortunately I do not know how to make this work on linux. Have you tried googling the error? If you want to port it to some other language I can give you guidance but otherwise I think I can't help. I could port it to .NET core which would run crossplatform (without a GUI) but that would require a lot of work since I don't really play the game anymore I don't really have the motivation to do so.
